workaround weird mypy failure w/bogus error message
Somehow, an f-string in an assert statement causes mypy to fail and exit with
    models/ecoli/analysis/single/evaluationTime.py:1:9: error: invalid syntax  [syntax]
but only on Sherlock. And source line 1 (`from __future__ import...` or a blank
line, or a comment, or a docstring) has nothing to do with it.