mypy.sh: freeze on mypy==0.770 for now
... since mypy 0.780+ issues 2 type check errors for tsv. See https://github.com/python/typeshed/issues/4349

```
wholecell/io/tsv.py:33:36: error: Argument 1 to "TextIOWrapper" has incompatible type "IO[bytes]"; expected "BinaryIO"  [arg-type]
wholecell/io/tsv.py:77:5: error: Argument 1 to "TextIOWrapper" has incompatible type "IO[bytes]"; expected "BinaryIO"  [arg-type]
```