operons off/on/both in manual analysis scripts
`analysisParca` now runs its analyses on the primary Parca output (kb/) and again on the secondary Parca output (kb-poly/), if present.

`analysisSingle`, `analysisMultigen`, `analysisCohort`, and `buildCausalityNetwork` already take a `--variant-index VARIANT_INDEX` option. That selects between the monocistronic and polycistronic variants in the `both` case since `makeVariant` assigns them different variant index numbers.

`analysisVariant` lists all the variants generated, whether operons are off/on/both, but it only feeds the primary (kb/) Parca sim_data and validation_data into `do_plot()`, so the `both` case more work to also use the `kb-poly/` simData & validationData files for variants with `index >= 100000`.

I'll update fw_queue and wcm workflows soon.

I'm not planning to make these utilities load the secondary Parca output:
* runscripts/manual/parameter_search.py, runscripts/fileManipulation/addNonPdfPlots.py, colony/processes/wcecoli.py, runscripts/debug/load_sim_data.py, runscripts/debug/compare_expression_probabilities.py, runscripts/debug/parca_size.py, runscripts/metrics/behavior_metrics/behavior_metrics.py, wholecell/optimization/base_solver.py.

Note: One of the CORE multigen analysis class produced a traceback in the polycistron case, but that might be due to running all the sims for longly 5 seconds:

    > python runscripts/manual/runSim.py now-2 --operons both -v condition 0 1 -g2 -s100 -i2 --length-sec 5

```
  File "/Users/jerry/dev/wcEcoli/models/ecoli/analysis/multigen/aa_supply_enzymes.py", line 58, in do_plot
    enzyme_rna_indices = np.array([rna_data_indices[cistron + '[c]'] for cistron in cistrons])
  File "/Users/jerry/dev/wcEcoli/models/ecoli/analysis/multigen/aa_supply_enzymes.py", line 58, in <listcomp>
    enzyme_rna_indices = np.array([rna_data_indices[cistron + '[c]'] for cistron in cistrons])
KeyError: 'EG11226_RNA[c]'
```

Ditto in `cohort/proteinCopyNumberDistribution.py`:

```
  File "/Users/jerry/dev/wcEcoli/models/ecoli/analysis/cohort/proteinCopyNumberDistribution.py", line 75, in do_plot
    idx_timepoint = np.random.randint(0, high=len(time))
TypeError: len() of unsized object
```

and in `variant/growthConditionComparison.py`:

```
  File "/Users/jerry/dev/wcEcoli/models/ecoli/analysis/variant/growthConditionComparison.py", line 70, in do_plot
    stableRnaSynth = np.sum(rnaSynth[:,isTRna], axis=1) + np.sum(rnaSynth[:,isRRna], axis=1)
IndexError: boolean index did not match indexed array along dimension 1; dimension is 3459 but corresponding boolean dimension is 4692
```